apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - keycloak.yaml
  - backend.yaml
  - worker.yaml
  - portals.yaml
  - mailhog.yaml

images:
  - name: git.lupulup.com/admin/careerforge-backend
    newTag: latest
  - name: git.lupulup.com/admin/careerforge-employee
    newTag: dev
  - name: git.lupulup.com/admin/careerforge-coach
    newTag: dev
  - name: git.lupulup.com/admin/careerforge-manager
    newTag: dev
  - name: git.lupulup.com/admin/careerforge-admin
    newTag: dev
