apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-marketing-site
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: site=git.lupulup.com/admin/marketing-site
    argocd-image-updater.argoproj.io/site.update-strategy: digest
    argocd-image-updater.argoproj.io/site.image-name: git.lupulup.com/admin/marketing-site
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/site.kustomize.image-name: git.lupulup.com/admin/marketing-site
spec:
  project: default
  source:
    repoURL: https://git.lupulup.com/admin/BankOfferingAI.git
    targetRevision: HEAD
    path: k8s/marketing-site
  destination:
    server: https://kubernetes.default.svc
    namespace: cf-marketing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
