apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: git.lupulup.com/admin/marketing-site
    newTag: 40e27824a7c0ef1cdacd23ebb2d2cf798c321852
